### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by Dovuq** [xrdrsp/xrdrsp.github.io#5]
change .gitignore into

```
template.html
*.DS_Store
$RECYCLE.bin
System Volumn Information
```

**Comment by xrdrsp** [comment]
Thanks!

**Comment by Dovuq** [comment]
even though it's useless for you.

**Comment by Dovuq** [comment]
@xrdrsp Volumn -> Volume

**Comment by xrdrsp** [comment]
> @xrdrsp Volumn -> Volume

yeah.

@Dovuq

**Comment by Dovuq** [comment]
turn to https://github.com/xrdrsp/junk/pull/6
