### ISSUE TITLE
advise to add valine

### ISSUE THREAD

**Issue by Dovuq** [xrdrsp/xrdrsp.github.io#9]
@xrdrsp RT

**Comment by xrdrsp** [comment]
I tried but I didn't make it.

**Comment by Dovuq** [comment]
ah.

**Comment by xrdrsp** [comment]
The html just did not work.

**Comment by Dovuq** [comment]
You've deleted it. @xrdrsp

**Comment by xrdrsp** [comment]
@Dovuq I tried again, but failed... so i would use cusdis.

**Comment by Dovuq** [comment]
@xrdrsp Looking forward to it!

**Comment by xrdrsp** [comment]
I already added cusdis

**Comment by xrdrsp** [comment]
@Dovuq

**Comment by Dovuq** [comment]
Please note that your messages will only be displayed here once they get approved by [xrdrsp](https://xrdrsp.github.io/) when using [Cusdis](https://cusdis.com/).

**Comment by Dovuq** [comment]
......

**Comment by Dovuq** [comment]
@xrdrsp

**Comment by xrdrsp** [comment]
it must be like this; i cant modify whether to check comments @ Dovuq

**Comment by xrdrsp** [comment]
@Dovuq

**Comment by Dovuq** [comment]
euqqqquei. @xrdrsp

**Comment by xrdrsp** [comment]
rustill at zhzx? @Dovuq

**Comment by Dovuq** [comment]
I'm still positive......

**Comment by xrdrsp** [comment]
ah.

**Comment by Dovuq** [comment]
normally should be at zhzx at present

**Comment by xrdrsp** [comment]
eq.

**Comment by Dovuq** [comment]
can you approve my comments

cusdis

pls

@xrdrsp

**Comment by xrdrsp** [comment]
i have approved @Dovuq

**Comment by Dovuq** [comment]
Hooray! @xrdrsp
